// Code generated by protoc-gen-go.
// source: request.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	request.proto

It has these top-level messages:
	RequestVo
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestVo_SourceType int32

const (
	RequestVo_IOS     RequestVo_SourceType = 1
	RequestVo_ANDROID RequestVo_SourceType = 2
	RequestVo_WEB     RequestVo_SourceType = 3
)

var RequestVo_SourceType_name = map[int32]string{
	1: "IOS",
	2: "ANDROID",
	3: "WEB",
}
var RequestVo_SourceType_value = map[string]int32{
	"IOS":     1,
	"ANDROID": 2,
	"WEB":     3,
}

func (x RequestVo_SourceType) Enum() *RequestVo_SourceType {
	p := new(RequestVo_SourceType)
	*p = x
	return p
}
func (x RequestVo_SourceType) String() string {
	return proto.EnumName(RequestVo_SourceType_name, int32(x))
}
func (x *RequestVo_SourceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestVo_SourceType_value, data, "RequestVo_SourceType")
	if err != nil {
		return err
	}
	*x = RequestVo_SourceType(value)
	return nil
}
func (RequestVo_SourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type RequestVo struct {
	UserId           *string               `protobuf:"bytes,1,req,name=userId" json:"userId,omitempty"`
	Source           *RequestVo_SourceType `protobuf:"varint,2,opt,name=source,enum=model.RequestVo_SourceType,def=1" json:"source,omitempty"`
	Content          *string               `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	SourceId         *string               `protobuf:"bytes,4,req,name=sourceId" json:"sourceId,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *RequestVo) Reset()                    { *m = RequestVo{} }
func (m *RequestVo) String() string            { return proto.CompactTextString(m) }
func (*RequestVo) ProtoMessage()               {}
func (*RequestVo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_RequestVo_Source RequestVo_SourceType = RequestVo_IOS

func (m *RequestVo) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *RequestVo) GetSource() RequestVo_SourceType {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return Default_RequestVo_Source
}

func (m *RequestVo) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *RequestVo) GetSourceId() string {
	if m != nil && m.SourceId != nil {
		return *m.SourceId
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestVo)(nil), "model.RequestVo")
	proto.RegisterEnum("model.RequestVo_SourceType", RequestVo_SourceType_name, RequestVo_SourceType_value)
}

func init() { proto.RegisterFile("request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd,
	0x51, 0x9a, 0xcb, 0xc8, 0xc5, 0x19, 0x04, 0x91, 0x08, 0xcb, 0x17, 0xe2, 0xe3, 0x62, 0x2b, 0x2d,
	0x4e, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x14, 0x32, 0xe0, 0x62, 0x2b, 0xce,
	0x2f, 0x2d, 0x4a, 0x4e, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x33, 0x92, 0xd6, 0x03, 0xeb, 0xd2,
	0x83, 0xeb, 0xd0, 0x0b, 0x06, 0x4b, 0x87, 0x54, 0x16, 0xa4, 0x5a, 0x31, 0x7b, 0xfa, 0x07, 0x0b,
	0xf1, 0x73, 0xb1, 0x27, 0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x48, 0x30, 0x83, 0x8d, 0x10, 0xe0,
	0xe2, 0x80, 0x18, 0xe1, 0x99, 0x22, 0xc1, 0x02, 0x12, 0x51, 0xd2, 0xe6, 0xe2, 0x42, 0xe8, 0x12,
	0x62, 0xe7, 0x02, 0xe9, 0x13, 0x60, 0x14, 0xe2, 0xe6, 0x62, 0x77, 0xf4, 0x73, 0x09, 0xf2, 0xf7,
	0x74, 0x11, 0x60, 0x02, 0x89, 0x86, 0xbb, 0x3a, 0x09, 0x30, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x89, 0xcc, 0x1b, 0xa2, 0xb6, 0x00, 0x00, 0x00,
}
